### ISSUE TITLE
Feedback of Assignment

### ISSUE THREAD

**Issue by aakashchavan-qa** [DeepakGarg1700/automation-assignment#1]
Hi Deepak,

I've reviewed all files of your code briefly. There are some points, Please solve it first so I can check it again.
1. There are not any success/failure message on action perform.
2. Use file name as per code functionality instead of test1 etc.
3. Use single method for log-in, log-out on every page, It is increasing code complexity. 
4. In all test case try to perform more assertions such as (title,text or current url) etc.
5. There is one test case(test7.js)failed.

```
Test Case result  ─± nightwatch --test               

[Test7] Test Suite
==================

Running:  login to rtmedia demo
 ✔ Element <body> was visible after 262 milliseconds.
 ✔ Testing if the page title equals "rtMedia Demo Site".
 ✔ Testing if element <.logout> is visible.
 ✖ Testing if value of <#message p> contains: "Changes saved.". Element does not have a value attribute.  - expected "true" but got: null

FAILED:  1 assertions failed and 3 passed (50.894s)

```

Please solve above points and let me know, so I can resume the review again.

Thanks.

**Comment by DeepakGarg1700** [comment]
Thanks for your reply.
I shall revert you soon.

**Comment by DeepakGarg1700** [comment]
Hello Akash

I have made changes according to your requirements. Please check and revert me if any doubt.

Regarding 

> There is one test case(test7.js)failed.

Test case is running fine on my end. Please note i am using 25 inch monitor, may be that is the reason test case is not failing in big screen.However when i tried to switch on my laptop screen test case do failed. 
So i would conclude that the issue could might be with the NightwatchJS API.

I could not find any solution for the small screen problem. However there is an hack that could be implemented to bypass this error.

Press `cntrl` + `-` when firefox start . That would zoom out the screen. This solution worked for me .

```
[Test7 Profile Should Be Updated Successfully] Test Suite
=========================================================

Running:  login to rtmedia demo
 ? Element <body> was visible after 138 milliseconds.
 ? Testing if the page title equals "rtMedia Demo Site".
 ? Testing if element <.logout> is visible.
 ? Testing if element <#message> is visible.

OK. 4 assertions passed. (40.088s)
```

Thanks & Regards
Deepak Garg
